# Generated by Django 4.0.4 on 2022-05-02 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_group_managers'),
        ('social', '0005_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('auth.group',),
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
