# Generated by Django 4.0.4 on 2022-05-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_group_delete_grouping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
