# Generated by Django 4.0.4 on 2022-05-02 08:49

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_group_managers'),
        ('social', '0008_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='group_name')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='group_permissions')),
            ],
            options={
                'verbose_name': 'social_group',
                'verbose_name_plural': 'social_groups',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
