# Generated by Django 4.0.4 on 2022-05-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_socialgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialgroup',
            old_name='permissions',
            new_name='group_permissions',
        ),
    ]
