# Generated by Django 4.0.4 on 2022-05-02 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_permissions_socialgroup_group_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='socialgroup',
            managers=[
                ('objects', social.models.SocialGroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='admin_username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
