# Generated by Django 4.0.4 on 2022-05-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_socialgroup_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialgroup',
            name='posts',
            field=models.ManyToManyField(blank=True, to='social.post', verbose_name='posts'),
        ),
        migrations.AddField(
            model_name='socialgroup',
            name='user_list',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialgroup',
            name='admin_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
