# Generated by Django 4.0.4 on 2022-05-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_remove_comment_post_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='social.comment'),
        ),
    ]
